/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sdogu
 */
public class AlanAyarJFrame extends javax.swing.JFrame {

    /**
     * Creates new form AlanAyarJFrame
     */
    public AlanAyarJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField_aciklama = new javax.swing.JTextField();
        jLabel_aciklama = new javax.swing.JLabel();
        jLabel_alan6 = new javax.swing.JLabel();
        jTextField_alan6 = new javax.swing.JTextField();
        jLabel_alan5 = new javax.swing.JLabel();
        jTextField_alan5 = new javax.swing.JTextField();
        jLabel_alan4 = new javax.swing.JLabel();
        jTextFieldalan4 = new javax.swing.JTextField();
        jLabel_alan3 = new javax.swing.JLabel();
        jTextField_alan3 = new javax.swing.JTextField();
        jLabel_alan2 = new javax.swing.JLabel();
        jTextField_alan2 = new javax.swing.JTextField();
        jLabel_alan1 = new javax.swing.JLabel();
        jTextField_alan1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextField_aciklama.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_aciklama.setText("jTextField1");

        jLabel_aciklama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_aciklama.setText("Alan 7");

        jLabel_alan6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_alan6.setText("Alan 6");

        jTextField_alan6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_alan6.setText("jTextField1");

        jLabel_alan5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_alan5.setText("Alan 5");

        jTextField_alan5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_alan5.setText("jTextField1");

        jLabel_alan4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_alan4.setText("Alan 4");

        jTextFieldalan4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldalan4.setText("jTextField1");

        jLabel_alan3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_alan3.setText("Alan 3");

        jTextField_alan3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_alan3.setText("jTextField1");

        jLabel_alan2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_alan2.setText("Alan 2");

        jTextField_alan2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_alan2.setText("jTextField1");

        jLabel_alan1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_alan1.setText("Alan 1");

        jTextField_alan1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_alan1.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_aciklama, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_aciklama))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_alan6, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_alan6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_alan5, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_alan5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_alan4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldalan4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_alan3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_alan3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_alan1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_alan1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_alan2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_alan2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_alan1)
                    .addComponent(jLabel_alan1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_alan2)
                    .addComponent(jLabel_alan2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_alan3)
                    .addComponent(jLabel_alan3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldalan4)
                    .addComponent(jLabel_alan4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_alan5)
                    .addComponent(jLabel_alan5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_alan6)
                    .addComponent(jLabel_alan6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_aciklama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_aciklama, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlanAyarJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlanAyarJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlanAyarJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlanAyarJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlanAyarJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_aciklama;
    private javax.swing.JLabel jLabel_alan1;
    private javax.swing.JLabel jLabel_alan2;
    private javax.swing.JLabel jLabel_alan3;
    private javax.swing.JLabel jLabel_alan4;
    private javax.swing.JLabel jLabel_alan5;
    private javax.swing.JLabel jLabel_alan6;
    private javax.swing.JTextField jTextField_aciklama;
    private javax.swing.JTextField jTextField_alan1;
    private javax.swing.JTextField jTextField_alan2;
    private javax.swing.JTextField jTextField_alan3;
    private javax.swing.JTextField jTextField_alan5;
    private javax.swing.JTextField jTextField_alan6;
    private javax.swing.JTextField jTextFieldalan4;
    // End of variables declaration//GEN-END:variables
}
