/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sdogu
 */
public class AlanAyarJFrame extends javax.swing.JFrame {

    /**
     * Creates new form AlanAyarJFrame
     */
    database db = new database();
    public AlanAyarJFrame() {
        initComponents();
        db.readAlan();
        jTextField_alan1.setText(db.alanlar.get(0));
        jTextField_alan2.setText(db.alanlar.get(1));
        jTextField_alan3.setText(db.alanlar.get(2));
        jTextField_alan4.setText(db.alanlar.get(3));
        jTextField_alan5.setText(db.alanlar.get(4));
        jTextField_alan6.setText(db.alanlar.get(5));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_alan6 = new javax.swing.JLabel();
        jTextField_alan6 = new javax.swing.JTextField();
        jLabel_alan5 = new javax.swing.JLabel();
        jTextField_alan5 = new javax.swing.JTextField();
        jLabel_alan4 = new javax.swing.JLabel();
        jTextField_alan4 = new javax.swing.JTextField();
        jLabel_alan3 = new javax.swing.JLabel();
        jTextField_alan3 = new javax.swing.JTextField();
        jLabel_alan2 = new javax.swing.JLabel();
        jTextField_alan2 = new javax.swing.JTextField();
        jLabel_alan1 = new javax.swing.JLabel();
        jTextField_alan1 = new javax.swing.JTextField();
        jButton_kaydet = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel_alan6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_alan6.setText("Alan 6");

        jTextField_alan6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_alan6.setText("jTextField1");

        jLabel_alan5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_alan5.setText("Alan 5");

        jTextField_alan5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_alan5.setText("jTextField1");

        jLabel_alan4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_alan4.setText("Alan 4");

        jTextField_alan4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_alan4.setText("jTextField1");

        jLabel_alan3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_alan3.setText("Alan 3");

        jTextField_alan3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_alan3.setText("jTextField1");

        jLabel_alan2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_alan2.setText("Alan 2");

        jTextField_alan2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_alan2.setText("jTextField1");

        jLabel_alan1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_alan1.setText("Alan 1");

        jTextField_alan1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_alan1.setText("jTextField1");

        jButton_kaydet.setText("Kaydet");
        jButton_kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_kaydetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_kaydet, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel_alan6, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField_alan6))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel_alan5, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField_alan5))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel_alan4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField_alan4))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel_alan3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField_alan3))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel_alan1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField_alan1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel_alan2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField_alan2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_alan1)
                    .addComponent(jLabel_alan1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_alan2)
                    .addComponent(jLabel_alan2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_alan3)
                    .addComponent(jLabel_alan3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_alan4)
                    .addComponent(jLabel_alan4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_alan5)
                    .addComponent(jLabel_alan5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_alan6)
                    .addComponent(jLabel_alan6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_kaydet, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_kaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_kaydetActionPerformed
        // TODO add your handling code here:
        db.alanlar.set(0, jTextField_alan1.getText());
        db.alanlar.set(1, jTextField_alan2.getText());
        db.alanlar.set(2, jTextField_alan3.getText());
        db.alanlar.set(3, jTextField_alan4.getText());
        db.alanlar.set(4, jTextField_alan5.getText());
        db.alanlar.set(5, jTextField_alan6.getText());
        
        db.writeAlan();
        this.dispose();
    }//GEN-LAST:event_jButton_kaydetActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlanAyarJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlanAyarJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlanAyarJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlanAyarJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlanAyarJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_kaydet;
    private javax.swing.JLabel jLabel_alan1;
    private javax.swing.JLabel jLabel_alan2;
    private javax.swing.JLabel jLabel_alan3;
    private javax.swing.JLabel jLabel_alan4;
    private javax.swing.JLabel jLabel_alan5;
    private javax.swing.JLabel jLabel_alan6;
    private javax.swing.JTextField jTextField_alan1;
    private javax.swing.JTextField jTextField_alan2;
    private javax.swing.JTextField jTextField_alan3;
    private javax.swing.JTextField jTextField_alan4;
    private javax.swing.JTextField jTextField_alan5;
    private javax.swing.JTextField jTextField_alan6;
    // End of variables declaration//GEN-END:variables
}
